server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          # CORS 처리. 서비스모듈에서는 웹브라우저와 직접 통신하지 않으므로, cors처리 불필요.
          globalcors:
            cors-configurations:
              '[/**]':
                # 어떤 도메인을 허용할 거냐 라는 의미.
                # - << 대시를 통해 여러 도메인을 허용 가능하다 밑에는 예시
                allowedOrigins:
                  - '*'
#                  - 'http://localhost:3000'
                # - 'https://www.example.com'

                # GET, POST, PUT, DELETE 등의 HTTP 메서드 허용
                allowedMethods: '*'
                # HTTP 헤더에도 여러가지가 있는데 그 헤더들을 전부 허용하겠다라는 의미.
                allowedHeaders: '*'
                # 인증 정보 같은 것들을 사용할 수 있게 허용할 거나라는 의미.
#                allowCredentials: true // allowedOrigins * 와는 동시에 사용할 수 없기에 잠시 주석처리
                allowCredentials: false
          routes:
            - id: glemoa-reader
              predicates:
                # 1. /member-service/** url 패턴으로 요청이 들어온다면 어디로 갈거냐??
                - Path=/glemoa-reader/**
              filters:
                # StripPrefix : 첫번째 접두어를 제거후에 member-service로 http요청 전달
                # 우리는 url 형식을 /member-service/member/doLogin 이런 형식으로 요청을 할 거임.
                # 그래서 /member-service << 이 접두어는 없애고 요청을 보내도록 하기 위해서 접두어를 제거.
                - StripPrefix=1
                # 2. lb는 Eureka 한테 물어보는 거임. 나 어디로 가야하냐??
                # 그럼 Eureka는 이 서비스로 가라고 알려줌.
                # 이 이름들은 해당 서비스 이름인 application-name과 일치해야 함..
              uri: lb://glemoa-reader

            - id: glemoa-member
              predicates:
                # 1. /member-member/** url 패턴으로 요청이 들어온다면 어디로 갈거냐??
                - Path=/glemoa-member/**
              filters:
                # StripPrefix : 첫번째 접두어를 제거후에 member-service로 http요청 전달
                # 우리는 url 형식을 /member-service/member/doLogin 이런 형식으로 요청을 할 거임.
                # 그래서 /member-service << 이 접두어는 없애고 요청을 보내도록 하기 위해서 접두어를 제거.
                - StripPrefix=1
                # 2. lb는 Eureka 한테 물어보는 거임. 나 어디로 가야하냐??
                # 그럼 Eureka는 이 서비스로 가라고 알려줌.
                # 이 이름들은 해당 서비스 이름인 application-name과 일치해야 함..
              uri: lb://glemoa-member