eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # 유레카 서버가 어디에 있는지를 위치 정보를 여기다가 명시해 둔 것이다.
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    # Eureka한테 나의 이름을 알려주기 위해 이름 설정
    name: glemoa-gateway
  profiles:
    active: prod
#    active: local